/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class CreateUser extends javax.swing.JFrame {

    Files.LoginPage lPage = new Files.LoginPage();
    Files.Registration register = new Files.Registration();
    /**
     * Creates new form CreateUser
     */
    public CreateUser() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fnField = new javax.swing.JTextField();
        lnField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        userNField = new javax.swing.JTextField();
        pwField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        phField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        returnMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("______________________________");

        jLabel2.setText("________________________________");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("       Register");

        fnField.setText("First Name");
        fnField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnFieldFocusLost(evt);
            }
        });

        lnField.setText("Last Name");
        lnField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnFieldFocusLost(evt);
            }
        });

        emailField.setText("Email");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        userNField.setText("User Name");
        userNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNFieldFocusLost(evt);
            }
        });

        pwField.setText("Password");
        pwField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwFieldFocusLost(evt);
            }
        });

        ageField.setText("Age");
        ageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFieldFocusLost(evt);
            }
        });

        phField.setText("Phone Number");
        phField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phFieldFocusLost(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(returnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)
                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fnField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ageField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lnField)
                                        .addComponent(phField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lnField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(fnField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(phField))
                .addGap(28, 28, 28)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userNField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        while(register.check(fnField.getText(), lnField.getText(), ageField.getText(), phField.getText(), emailField.getText())==false ){
           returnMessage.setText(register.checkInfo(fnField.getText(), lnField.getText(), ageField.getText(), phField.getText(), emailField.getText()));
           returnMessage. setHorizontalAlignment(SwingConstants. CENTER);
           returnMessage.setForeground(Color.red); 
        break;
        }
        if("User Name".equalsIgnoreCase(userNField.getText())){
            returnMessage.setText("Please enter username");
            returnMessage. setHorizontalAlignment(SwingConstants. CENTER);
            returnMessage.setForeground(Color.red);
        }
        else if(lPage.checkUserName(userNField.getText())){
            returnMessage.setText("This username is used");
            returnMessage. setHorizontalAlignment(SwingConstants. CENTER);
            returnMessage.setForeground(Color.red);
        }
        else if("Password".equalsIgnoreCase(pwField.getText())){
            returnMessage.setText("Please enter a password");
            returnMessage. setHorizontalAlignment(SwingConstants. CENTER);
            returnMessage.setForeground(Color.red);     
        }
        else if(register.check(fnField.getText(), lnField.getText(), ageField.getText(), phField.getText(), emailField.getText())==true){
            register.adduser(fnField.getText(), lnField.getText(), ageField.getText(), phField.getText(), emailField.getText());
            lPage.addLogin(userNField.getText().replaceAll("\\s+",""), pwField.getText());
            this.dispose();
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fnField.setForeground(Color.gray);
        lnField.setForeground(Color.gray);
        ageField.setForeground(Color.gray);
        emailField.setForeground(Color.gray);
        phField.setForeground(Color.gray);
        userNField.setForeground(Color.gray);
        pwField.setForeground(Color.gray);
    }//GEN-LAST:event_formWindowOpened

    private void fnFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFieldFocusGained
        if(fnField.getText().equalsIgnoreCase("First Name")){
            fnField.setText("");
            fnField.setForeground(Color.black);
        }
    }//GEN-LAST:event_fnFieldFocusGained

    private void fnFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFieldFocusLost
        if(fnField.getText().isEmpty()){
            fnField.setText("First Name");
            fnField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_fnFieldFocusLost

    private void lnFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFieldFocusGained
        if(lnField.getText().equalsIgnoreCase("Last Name")){
            lnField.setText("");
            lnField.setForeground(Color.black);
        }
    }//GEN-LAST:event_lnFieldFocusGained

    private void lnFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFieldFocusLost
        if(lnField.getText().isEmpty()){
            lnField.setText("Last Name");
            lnField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_lnFieldFocusLost

    private void ageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusGained
        if(ageField.getText().equalsIgnoreCase("Age")){
            ageField.setText("");
            ageField.setForeground(Color.black);
        }
    }//GEN-LAST:event_ageFieldFocusGained

    private void ageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusLost
        if(ageField.getText().isEmpty()){
            ageField.setText("Age");
            ageField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ageFieldFocusLost

    private void phFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phFieldFocusGained
        if(phField.getText().equalsIgnoreCase("Phone Number")){
            phField.setText("");
            phField.setForeground(Color.black);
        }
    }//GEN-LAST:event_phFieldFocusGained

    private void phFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phFieldFocusLost
        if(phField.getText().isEmpty()){
            phField.setText("Phone Number");
            phField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_phFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        if(emailField.getText().equalsIgnoreCase("Email")){
            emailField.setText("");
            emailField.setForeground(Color.black);
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        if(emailField.getText().isEmpty()){
            emailField.setText("Email");
            emailField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void userNFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNFieldFocusGained
        if(userNField.getText().equalsIgnoreCase("User Name")){
            userNField.setText("");
            userNField.setForeground(Color.black);
        }
    }//GEN-LAST:event_userNFieldFocusGained

    private void userNFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNFieldFocusLost
        if(userNField.getText().isEmpty()){
            userNField.setText("User Name");
            userNField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_userNFieldFocusLost

    private void pwFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwFieldFocusGained
        if(pwField.getText().equalsIgnoreCase("Password")){
            pwField.setText("");
            pwField.setForeground(Color.black);
        }
    }//GEN-LAST:event_pwFieldFocusGained

    private void pwFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwFieldFocusLost
        if(pwField.getText().isEmpty()){
            pwField.setText("Password");
            pwField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pwFieldFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateUser().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fnField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lnField;
    private javax.swing.JTextField phField;
    private javax.swing.JTextField pwField;
    private javax.swing.JLabel returnMessage;
    private javax.swing.JTextField userNField;
    // End of variables declaration//GEN-END:variables
}
